export default Types = {
    //MOVIE TYPES

    FECTH_LIST_MOVIES_REQUEST: 'FECTH_LIST_MOVIES_REQUEST',
    FECTH_LIST_MOVIES_SUCCESS: 'FECTH_LIST_MOVIES_SUCCESS',
    FECTH_LIST_MOVIES_FAILURE: 'FECTH_LIST_MOVIES_FAILURE',
    REFRESH_LIST_MOVIES: 'REFRESH_LIST_MOVIES',
    SEARCH_MOVIE_WITH_NAME_SUCCESS: 'SEARCH_MOVIE_WITH_NAME_SUCCESS',

}